export type AccentTone = "lime" | "mint" | "pink" | "gold";
export type CategoryAccent = AccentTone | "violet" | "blue";
export type BadgeTone = "top" | "new" | "hot" | null;

export const marqueeItems = [
  "Вэб хөгжүүлэлт",
  "UI/UX Дизайн",
  "Мобайл апп",
  "Лого & Брэнд",
  "Контент бичих",
  "Өгөгдлийн шинжилгээ",
  "SEO & Маркетинг",
  "Видео засварлах",
];

export const quickTags = [
  { label: "Вэб сайт", term: "Вэб сайт" },
  { label: "Лого дизайн", term: "Лого дизайн" },
  { label: "React", term: "React хөгжүүлэлт" },
  { label: "Мобайл апп", term: "Мобайл апп" },
  { label: "SEO", term: "SEO" },
  { label: "Видео засварлах", term: "Видео засварлах" },
  { label: "Нийтлэл", term: "Нийтлэл бичих" },
];

export const freelancerCards = [
  {
    initials: "Б",
    accent: "lime" as AccentTone,
    badge: "Шилдэг",
    badgeTone: "top" as BadgeTone,
    name: "Болд Г.",
    role: "Full-stack хөгжүүлэгч",
    description: "React, Node.js болон TypeScript ашиглан хурдан, найдвартай вэб апп бүтээнэ.",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    stars: "★★★★★",
    rating: "4.9",
    reviews: "42",
    price: "20,000₮/цаг",
  },
  {
    initials: "С",
    accent: "mint" as AccentTone,
    badge: "Шинэ",
    badgeTone: "new" as BadgeTone,
    name: "Сарнай Б.",
    role: "UI/UX Дизайнер",
    description: "Figma ашиглан хэрэглэгчдэд таатай, гоёмсог дизайн бүтээнэ.",
    skills: ["Figma", "Prototyping", "Branding"],
    stars: "★★★★★",
    rating: "4.8",
    reviews: "28",
    price: "25,000₮/цаг",
  },
  {
    initials: "Э",
    accent: "pink" as AccentTone,
    badge: "Эрэлттэй",
    badgeTone: "hot" as BadgeTone,
    name: "Эрдэнэ Ч.",
    role: "Мобайл хөгжүүлэгч",
    description: "iOS болон Android платформд зориулсан мобайл апп хийнэ.",
    skills: ["Flutter", "Swift", "Kotlin", "Firebase"],
    stars: "★★★★★",
    rating: "5.0",
    reviews: "15",
    price: "30,000₮/цаг",
  },
  {
    initials: "Н",
    accent: "gold" as AccentTone,
    badge: null,
    badgeTone: null as BadgeTone,
    name: "Номин О.",
    role: "Контент бичигч",
    description: "Монгол, Англи хэлээр маркетинг контент, блог, нийтлэл бичнэ.",
    skills: ["Copywriting", "SEO", "Blog"],
    stars: "★★★★☆",
    rating: "4.7",
    reviews: "61",
    price: "15,000₮/цаг",
  },
  {
    initials: "Г",
    accent: "lime" as AccentTone,
    badge: "Шилдэг",
    badgeTone: "top" as BadgeTone,
    name: "Ганхуяг Д.",
    role: "Өгөгдлийн шинжээч",
    description: "Python, SQL, Tableau ашиглан өгөгдлийн шинжилгээ, визуализаци хийнэ.",
    skills: ["Python", "SQL", "Tableau", "ML"],
    stars: "★★★★★",
    rating: "4.9",
    reviews: "19",
    price: "20,000₮/цаг",
  },
  {
    initials: "М",
    accent: "mint" as AccentTone,
    badge: null,
    badgeTone: null as BadgeTone,
    name: "Мөнхзул Р.",
    role: "График дизайнер",
    description: "Лого, брэнд айдентити, хэвлэлийн материал, соошиал медиа дизайн.",
    skills: ["Illustrator", "Photoshop", "Branding"],
    stars: "★★★★☆",
    rating: "4.6",
    reviews: "34",
    price: "25,000₮/цаг",
  },
];

export const categories = [
  { icon: "⌨", name: "Вэб хөгжүүлэлт", count: "340+ мэргэжилтэн", accent: "lime" as CategoryAccent, filter: "Вэб" },
  { icon: "◈", name: "UI/UX Дизайн", count: "210+ мэргэжилтэн", accent: "mint" as CategoryAccent, filter: "Дизайн" },
  { icon: "▣", name: "Мобайл апп", count: "180+ мэргэжилтэн", accent: "pink" as CategoryAccent, filter: "Мобайл" },
  { icon: "◎", name: "Маркетинг & SEO", count: "290+ мэргэжилтэн", accent: "gold" as CategoryAccent, filter: "Маркетинг" },
  { icon: "✦", name: "Контент & Бичих", count: "440+ мэргэжилтэн", accent: "violet" as CategoryAccent, filter: "Контент" },
  { icon: "⬡", name: "Өгөгдөл & AI", count: "120+ мэргэжилтэн", accent: "blue" as CategoryAccent, filter: "Өгөгдөл" },
];

export const howSteps = [
  {
    number: "01",
    title: "Захиалга нийтлэх",
    description: "Хэрэгтэй ажлаа тодорхой бичиж, төсвөө зааж захиалга оруулна уу.",
  },
  {
    number: "02",
    title: "Саналуудыг хүлээн авах",
    description: "Freelancer-ууд таны захиалгад санал ирүүлнэ. Профайл, үнэ, туршлагыг нь харьцуулна уу.",
  },
  {
    number: "03",
    title: "Хамтран ажиллах",
    description: "Сонгосон мэргэжилтэнтэйгээ мессеж, видео дуудлагаар харилцаж ажил хийнэ.",
  },
  {
    number: "04",
    title: "Хүлээж авах & Төлбөр",
    description: "Ажил дууссан, сэтгэл хангалуун үед л төлбөр хийнэ. 100% аюулгүй.",
  },
];

export const testimonials = [
  {
    quote: "Зарим platform дээр мэргэжилтэн олох хэцүү байдаг байсан. Zeel дээр 2 хоногт л хариу ирж ажлаа дуусгасан.",
    name: "Дэлгэрмаа Т.",
    role: "CEO, Fintech startup",
    initials: "Д",
    accent: "lime" as AccentTone,
  },
  {
    quote: "Манай компанийн вэб сайтыг хийлгэсэн. Болдын ажил маш мэргэжлийн, хугацаандаа дууссан. Дахин ажиллана.",
    name: "Батбаяр О.",
    role: "Маркетингийн захирал",
    initials: "Б",
    accent: "mint" as AccentTone,
  },
  {
    quote: "Эрдэнэ маань Flutter-ээр апп хийж өгсөн. App Store-д нийтлэгдэж, 1000+ хэрэглэгч татаж авлаа!",
    name: "Нарангэрэл Б.",
    role: "Бизнес эзэмшигч",
    initials: "Н",
    accent: "pink" as AccentTone,
  },
];

export type LandingCategoryKey = "web" | "design" | "mobile" | "marketing" | "content" | "data";

export type LandingCategory = {
  key: LandingCategoryKey;
  icon: string;
  name: string;
  count: string;
  accent: CategoryAccent;
  filter: string;
  description: string;
  keywords: string[];
  tags: string[];
};

export type SeedLandingJob = {
  id: string;
  title: string;
  companyName: string;
  location: string;
  employmentType: string;
  salary: string;
  description: string;
  createdAt: string;
  createdByName: null;
  categoryKey: LandingCategoryKey;
  tags: string[];
  highlight: string;
  level: string;
};

export type JobBoardFilter = "all" | "popular" | "highApplicants";

export const jobBoardFilters: Array<{
  key: JobBoardFilter;
  label: string;
  description: string;
}> = [
  { key: "all", label: "All job", description: "Бүх ажлыг харуулна" },
  { key: "popular", label: "Popular job", description: "Өндөр цалинтай ажлууд" },
  { key: "highApplicants", label: "Их CV авсан", description: "Олон applicant-тэй ажлууд" },
];

export const landingCategories: LandingCategory[] = [
  {
    key: "web",
    icon: "⌘",
    name: "Вэб хөгжүүлэлт",
    count: "10 ажлын санал",
    accent: "lime",
    filter: "Вэб",
    description: "Next.js, SaaS dashboard, e-commerce, CMS, performance optimization.",
    keywords: ["вэб", "web", "react", "next", "frontend", "backend", "full stack", "shopify", "wordpress"],
    tags: ["Next.js", "React", "TypeScript", "Node.js"],
  },
  {
    key: "design",
    icon: "◈",
    name: "UI/UX дизайн",
    count: "10 ажлын санал",
    accent: "mint",
    filter: "Дизайн",
    description: "Product design, design systems, brand identity, motion, UX research.",
    keywords: ["дизайн", "design", "ux", "ui", "figma", "branding", "prototype", "visual", "motion"],
    tags: ["Figma", "Prototype", "Wireframe", "Branding"],
  },
  {
    key: "mobile",
    icon: "▣",
    name: "Мобайл апп",
    count: "10 ажлын санал",
    accent: "pink",
    filter: "Мобайл",
    description: "Flutter, React Native, iOS, Android, fintech and commerce apps.",
    keywords: ["мобайл", "mobile", "flutter", "react native", "ios", "android", "swift", "kotlin"],
    tags: ["Flutter", "React Native", "iOS", "Android"],
  },
  {
    key: "marketing",
    icon: "◎",
    name: "Маркетинг & SEO",
    count: "10 ажлын санал",
    accent: "gold",
    filter: "Маркетинг",
    description: "SEO growth, paid acquisition, CRM, analytics, retention campaigns.",
    keywords: ["маркетинг", "seo", "growth", "ads", "performance", "crm", "retention", "analytics"],
    tags: ["SEO", "Meta Ads", "GA4", "Email CRM"],
  },
  {
    key: "content",
    icon: "✦",
    name: "Контент & бичих",
    count: "10 ажлын санал",
    accent: "violet",
    filter: "Контент",
    description: "Copywriting, scripts, articles, editorial planning, localization.",
    keywords: ["контент", "copy", "writer", "script", "article", "blog", "editor", "social copy"],
    tags: ["Copywriting", "Script", "Editorial", "Localization"],
  },
  {
    key: "data",
    icon: "⬡",
    name: "Өгөгдөл & AI",
    count: "10 ажлын санал",
    accent: "blue",
    filter: "Өгөгдөл",
    description: "Analytics, BI, ML pipelines, prompt workflows, dashboards and reporting.",
    keywords: ["өгөгдөл", "data", "analytics", "sql", "python", "machine learning", "ai", "llm", "bi"],
    tags: ["SQL", "Python", "Power BI", "Machine Learning"],
  },
];

export const landingCategoryOptions = [
  { value: "all", label: "Бүх ангилал" },
  ...landingCategories.map((category) => ({
    value: category.key,
    label: category.name,
  })),
];

const SEED_BASE_TIMESTAMP = Date.parse("2026-04-21T09:00:00.000Z");

function seedDate(dayOffset: number, hourOffset = 0) {
  return new Date(SEED_BASE_TIMESTAMP - dayOffset * 24 * 60 * 60 * 1000 - hourOffset * 60 * 60 * 1000).toISOString();
}

type SeedSpec = {
  title: string;
  companyName: string;
  location: string;
  employmentType: string;
  salary: string;
  description: string;
  tags: string[];
  highlight: string;
  level: string;
  dayOffset: number;
  hourOffset?: number;
};

const seedJobMatrix: Record<LandingCategoryKey, SeedSpec[]> = {
  web: [
    {
      title: "Senior Next.js Frontend Developer",
      companyName: "Nomad Commerce",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.8 - 6.2 сая ₮",
      description: "E-commerce storefront, checkout flow болон performance optimization дээр ажиллах frontend lead хайж байна.",
      tags: ["Next.js", "TypeScript", "SSR", "Tailwind"],
      highlight: "Core Web Vitals болон checkout conversion сайжруулах төсөл",
      level: "Senior",
      dayOffset: 0,
      hourOffset: 2,
    },
    {
      title: "React Dashboard Engineer",
      companyName: "FinSight Cloud",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "3.5 - 4.5 сая ₮",
      description: "B2B SaaS dashboard-ийн table, charts, permissions flow дээр туршлагатай инженер авна.",
      tags: ["React", "Charts", "Role Access", "API"],
      highlight: "Analytics dashboard-ийг 6 долоо хоногт шинэчилнэ",
      level: "Mid-Senior",
      dayOffset: 0,
      hourOffset: 5,
    },
    {
      title: "Full-stack Product Developer",
      companyName: "Steppe HR",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "4.2 - 5.4 сая ₮",
      description: "HR workflow SaaS дээр React, Node.js, MySQL ашиглан шинэ модуль гаргана.",
      tags: ["Node.js", "React", "MySQL", "REST API"],
      highlight: "Recruitment workflow-г production scale болгох ажил",
      level: "Senior",
      dayOffset: 1,
    },
    {
      title: "WordPress Performance Specialist",
      companyName: "Altan Media",
      location: "Remote / Ulaanbaatar",
      employmentType: "Хагас цаг",
      salary: "2.2 - 3.1 сая ₮",
      description: "Existing news portal-ийн WordPress theme, caching, ad script performance-ийг цэгцэлнэ.",
      tags: ["WordPress", "PHP", "Caching", "PageSpeed"],
      highlight: "LCP 2.5 секундээс доош буулгах зорилготой",
      level: "Mid",
      dayOffset: 1,
      hourOffset: 6,
    },
    {
      title: "Shopify Theme Developer",
      companyName: "Silk Route Store",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "3.0 - 3.8 сая ₮",
      description: "Shopify storefront localization, landing page, upsell flow хийх хөгжүүлэгч хэрэгтэй.",
      tags: ["Shopify", "Liquid", "A/B Test", "Localization"],
      highlight: "Mongolia + APAC зах зээлд зориулсан шинэ theme",
      level: "Mid",
      dayOffset: 2,
    },
    {
      title: "Backend API Developer",
      companyName: "Cargo Link",
      location: "Улаанбаатар / Remote",
      employmentType: "Бүтэн цаг",
      salary: "3.8 - 5.0 сая ₮",
      description: "Shipment tracking болон partner portal-ийн API architecture дээр төвлөрнө.",
      tags: ["Node.js", "PostgreSQL", "Auth", "Queue"],
      highlight: "High-volume logistics API-г шинэчлэх ажил",
      level: "Senior",
      dayOffset: 2,
      hourOffset: 4,
    },
    {
      title: "Frontend Developer for Booking Platform",
      companyName: "Blue Yurt Travel",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "3.2 - 4.1 сая ₮",
      description: "Tour booking funnel, itinerary builder, payment UI хийх React хөгжүүлэгч хайж байна.",
      tags: ["React", "Booking UX", "Payment UI", "Hooks"],
      highlight: "Seasonal campaign-тай уялдсан booking rebuild",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "CMS Integrator",
      companyName: "Bilig Edu",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "2.6 - 3.4 сая ₮",
      description: "Headless CMS-ийг сургалтын platform-той холбоод marketing page-уудыг динамик болгоно.",
      tags: ["CMS", "Sanity", "Next.js", "GraphQL"],
      highlight: "Content team-д no-code publishing workflow өгнө",
      level: "Mid",
      dayOffset: 3,
      hourOffset: 7,
    },
    {
      title: "QA Automation for Web Platform",
      companyName: "Khan Bank Labs",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "3.7 - 4.4 сая ₮",
      description: "Internet banking web flow дээр regression automation setup хийх QA инженер шаардлагатай.",
      tags: ["Playwright", "Testing", "CI", "Regression"],
      highlight: "Release cycle-ийг илүү найдвартай болгох ownership",
      level: "Mid-Senior",
      dayOffset: 4,
    },
    {
      title: "Junior Web Developer",
      companyName: "Ulemj Digital",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "2.0 - 2.6 сая ₮",
      description: "Landing page, CMS update, bug fix, QA handoff дээр ажиллах growth-minded junior хайж байна.",
      tags: ["HTML", "CSS", "JavaScript", "Responsive"],
      highlight: "Mentorship-тэй багт орж хурдан өсөх боломж",
      level: "Junior",
      dayOffset: 4,
      hourOffset: 5,
    },
  ],
  design: [
    {
      title: "Senior Product Designer",
      companyName: "Hunnu Pay",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.0 - 5.5 сая ₮",
      description: "Fintech app болон merchant dashboard-ийн core flow-уудыг redesign хийх product designer авна.",
      tags: ["Figma", "Flows", "Prototype", "Fintech"],
      highlight: "Payment onboarding conversion-д шууд нөлөөлөх ажил",
      level: "Senior",
      dayOffset: 0,
      hourOffset: 4,
    },
    {
      title: "UI Designer for SaaS Dashboard",
      companyName: "GerHub",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "2.8 - 3.6 сая ₮",
      description: "Operations dashboard-ийн component system болон dark/light mode-ийг шинэчилнэ.",
      tags: ["UI Kit", "Components", "Figma", "Dashboard"],
      highlight: "Engineering handoff бэлэн дизайн систем үүсгэнэ",
      level: "Mid",
      dayOffset: 1,
      hourOffset: 2,
    },
    {
      title: "Brand Identity Designer",
      companyName: "Altai Venture Studio",
      location: "Улаанбаатар",
      employmentType: "Гэрээт",
      salary: "3.2 - 4.0 сая ₮",
      description: "Шинэ venture-ийн logo, color system, pitch deck visual direction гаргах дизайнер хайж байна.",
      tags: ["Branding", "Identity", "Logo", "Deck"],
      highlight: "Startup launch pack бүтнээр нь гаргах төсөл",
      level: "Mid-Senior",
      dayOffset: 1,
      hourOffset: 7,
    },
    {
      title: "UX Researcher",
      companyName: "MobiCom Labs",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "3.4 - 4.3 сая ₮",
      description: "Consumer app дээр interview, usability test, synthesis хийж squad-д insight нийлүүлнэ.",
      tags: ["Research", "Usability", "Journey Map", "Insight"],
      highlight: "Monthly research sprint тогтмол явуулах ownership",
      level: "Mid",
      dayOffset: 2,
    },
    {
      title: "Design System Specialist",
      companyName: "Cloud Factory Asia",
      location: "Remote",
      employmentType: "Бүтэн цаг",
      salary: "3.8 - 4.8 сая ₮",
      description: "Multi-product design tokens, component governance, accessibility standard тогтооно.",
      tags: ["Design System", "Tokens", "Accessibility", "Figma"],
      highlight: "4 product багийг нэг системд нэгтгэнэ",
      level: "Senior",
      dayOffset: 2,
      hourOffset: 6,
    },
    {
      title: "Motion Graphics Designer",
      companyName: "Tengri Media House",
      location: "Улаанбаатар",
      employmentType: "Хагас цаг",
      salary: "2.4 - 3.2 сая ₮",
      description: "Launch campaign видео, social cutdown, app promo animation хийх motion designer авна.",
      tags: ["After Effects", "Motion", "Social", "Promo"],
      highlight: "Launch campaign-ийн гол визуал ачааг үүрнэ",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "Illustration Designer",
      companyName: "Kinder Box",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "2.1 - 2.9 сая ₮",
      description: "Kids learning app-ийн illustration system, stickers, onboarding visual хийх дизайнер хэрэгтэй.",
      tags: ["Illustration", "Visual Style", "Character", "App"],
      highlight: "Friendly product personality бүтээх чиг үүрэг",
      level: "Mid",
      dayOffset: 3,
      hourOffset: 5,
    },
    {
      title: "Landing Page Visual Designer",
      companyName: "Nomad Summit",
      location: "Улаанбаатар / Remote",
      employmentType: "Гэрээт",
      salary: "2.5 - 3.3 сая ₮",
      description: "Conference site-ийн hero visual, speaker layout, sponsor pages redesign хийх шаардлагатай.",
      tags: ["Web Design", "Layout", "Hero", "Visual Direction"],
      highlight: "Event launch-аас өмнө өндөр нөлөөтэй refresh",
      level: "Mid",
      dayOffset: 4,
    },
    {
      title: "Junior UI/UX Designer",
      companyName: "Oyu Apps",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "1.8 - 2.4 сая ₮",
      description: "Wireframe, visual cleanup, design QA, developer handoff дээр ажиллах junior дизайнер хайж байна.",
      tags: ["Wireframe", "Design QA", "Figma", "Junior"],
      highlight: "Senior mentor-той багт product pipeline үзнэ",
      level: "Junior",
      dayOffset: 4,
      hourOffset: 7,
    },
    {
      title: "Packaging & Print Designer",
      companyName: "Steppe Kitchen",
      location: "Улаанбаатар",
      employmentType: "Гэрээт",
      salary: "2.6 - 3.5 сая ₮",
      description: "New food line-ийн packaging, retail POS materials, social adaptation гаргана.",
      tags: ["Packaging", "Print", "Adobe", "Retail"],
      highlight: "Shelf impact өндөр бүтээгдэхүүний launch design",
      level: "Mid",
      dayOffset: 5,
    },
  ],
  mobile: [
    {
      title: "Senior Flutter Engineer",
      companyName: "QPay Ecosystem",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.5 - 5.8 сая ₮",
      description: "Payment app-ийн wallet, QR, loyalty module-ууд дээр Flutter lead инженер ажиллуулна.",
      tags: ["Flutter", "Bloc", "Payments", "Firebase"],
      highlight: "1M+ хэрэглэгчтэй flow дээр ownership",
      level: "Senior",
      dayOffset: 0,
      hourOffset: 3,
    },
    {
      title: "React Native App Developer",
      companyName: "Nomad Health",
      location: "Remote",
      employmentType: "Бүтэн цаг",
      salary: "3.6 - 4.7 сая ₮",
      description: "Telehealth app-ийн appointment, chat, notification module хөгжүүлнэ.",
      tags: ["React Native", "Expo", "Push", "Chat"],
      highlight: "Remote care app-ийн шинэ release cycle",
      level: "Mid-Senior",
      dayOffset: 1,
    },
    {
      title: "iOS Engineer",
      companyName: "Blue Finance",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "4.2 - 5.1 сая ₮",
      description: "Native iOS banking experience, secure auth, biometric flow дээр ажиллах Swift инженер хэрэгтэй.",
      tags: ["Swift", "iOS", "Biometric", "Secure Auth"],
      highlight: "App Store rating-ийг өсгөх quality initiative",
      level: "Senior",
      dayOffset: 1,
      hourOffset: 5,
    },
    {
      title: "Android Kotlin Developer",
      companyName: "EduTrack",
      location: "Remote / Ulaanbaatar",
      employmentType: "Бүтэн цаг",
      salary: "3.4 - 4.3 сая ₮",
      description: "Offline-first learning app дээр Kotlin, Room, sync logic дээр төвлөрч ажиллана.",
      tags: ["Kotlin", "Android", "Offline", "Sync"],
      highlight: "Low-connectivity орчинд оновчтой app build",
      level: "Mid",
      dayOffset: 2,
    },
    {
      title: "Mobile QA Automation Engineer",
      companyName: "TechBridge Studio",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "2.9 - 3.7 сая ₮",
      description: "Regression suite, release checklist, device matrix automation setup хийх QA хайж байна.",
      tags: ["Appium", "QA", "Device Lab", "Regression"],
      highlight: "Release reliability-г measurable болгоно",
      level: "Mid",
      dayOffset: 2,
      hourOffset: 6,
    },
    {
      title: "Flutter UI Integrator",
      companyName: "Ger Delivery",
      location: "Улаанбаатар",
      employmentType: "Хагас цаг",
      salary: "2.3 - 3.0 сая ₮",
      description: "Figma-гаас pixel-perfect screen integration, animation polish хийх frontend-heavy mobile developer авна.",
      tags: ["Flutter UI", "Animation", "Design Handoff", "Dart"],
      highlight: "Courier app-ийн user-facing redesign",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "React Native Growth Engineer",
      companyName: "Playgo Kids",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "3.0 - 3.8 сая ₮",
      description: "Subscription paywall, onboarding, referral flow-уудыг growth metric-тэй уялдуулж хөгжүүлнэ.",
      tags: ["React Native", "Growth", "Paywall", "Analytics"],
      highlight: "Trial-to-paid conversion сайжруулах зорилт",
      level: "Mid",
      dayOffset: 3,
      hourOffset: 4,
    },
    {
      title: "Junior Mobile Developer",
      companyName: "Ayar Tech",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "1.9 - 2.5 сая ₮",
      description: "Bug fix, feature support, release prep дээр ажиллах junior mobile engineer авна.",
      tags: ["Flutter", "Git", "Testing", "Junior"],
      highlight: "Production app дээр туршлага хуримтлуулах боломж",
      level: "Junior",
      dayOffset: 4,
    },
    {
      title: "Fintech Mobile Security Engineer",
      companyName: "Ard Secure",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.8 - 6.0 сая ₮",
      description: "Jailbreak detection, secure storage, risk signal integration дээр ажиллах mobile security engineer хайж байна.",
      tags: ["Security", "iOS", "Android", "Risk"],
      highlight: "High-trust payment stack дээр ажиллах роль",
      level: "Senior",
      dayOffset: 4,
      hourOffset: 6,
    },
    {
      title: "Mobile Product Engineer",
      companyName: "RideMGL",
      location: "Remote / Ulaanbaatar",
      employmentType: "Бүтэн цаг",
      salary: "3.7 - 4.9 сая ₮",
      description: "Rider and driver app-ийн shared architecture, feature rollout, analytics instrumentation дээр ажиллана.",
      tags: ["Mobile Product", "Analytics", "Feature Flags", "Architecture"],
      highlight: "Two-sided marketplace app-ийг scale хийх ажил",
      level: "Senior",
      dayOffset: 5,
    },
  ],
  marketing: [
    {
      title: "SEO Growth Specialist",
      companyName: "Mongol Travel Guide",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "2.8 - 3.9 сая ₮",
      description: "Organic traffic өсгөх technical SEO, topical clusters, search intent strategy дээр төвлөрнө.",
      tags: ["SEO", "Content Cluster", "GA4", "Search Console"],
      highlight: "6 сарын organic growth roadmap",
      level: "Mid-Senior",
      dayOffset: 0,
      hourOffset: 6,
    },
    {
      title: "Performance Marketing Manager",
      companyName: "StorePay Market",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.0 - 5.2 сая ₮",
      description: "Meta, Google, TikTok paid acquisition campaigns-ийг ROAS зорилготой удирдана.",
      tags: ["Meta Ads", "Google Ads", "ROAS", "Attribution"],
      highlight: "Scale budget болон creative testing ownership",
      level: "Senior",
      dayOffset: 1,
    },
    {
      title: "CRM & Email Automation Lead",
      companyName: "Khan Retail Club",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "3.4 - 4.4 сая ₮",
      description: "Lifecycle segmentation, loyalty journeys, email/SMS automation урсгалуудыг шинэчилнэ.",
      tags: ["CRM", "Email", "Retention", "Lifecycle"],
      highlight: "Repeat purchase өсгөх retention engine",
      level: "Mid-Senior",
      dayOffset: 1,
      hourOffset: 7,
    },
    {
      title: "Social Campaign Strategist",
      companyName: "Naadam Festival Office",
      location: "Улаанбаатар / Remote",
      employmentType: "Гэрээт",
      salary: "2.6 - 3.4 сая ₮",
      description: "Event кампани дээр social calendar, influencer brief, paid boost strategy гаргана.",
      tags: ["Social", "Campaign", "Influencer", "Calendar"],
      highlight: "Seasonal event awareness-ийн гол чиглүүлэгч",
      level: "Mid",
      dayOffset: 2,
    },
    {
      title: "B2B Demand Generation Specialist",
      companyName: "Steppe ERP",
      location: "Remote",
      employmentType: "Бүтэн цаг",
      salary: "3.5 - 4.6 сая ₮",
      description: "Webinar funnel, lead magnet, nurture sequence ашиглан pipeline growth хийнэ.",
      tags: ["Demand Gen", "LinkedIn", "Funnel", "Lead Nurture"],
      highlight: "Qualified pipeline-ийг маркетингаас бий болгох роль",
      level: "Mid-Senior",
      dayOffset: 2,
      hourOffset: 5,
    },
    {
      title: "Marketplace Growth Analyst",
      companyName: "Talst Market",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "3.0 - 3.8 сая ₮",
      description: "User acquisition, activation, retention funnel-уудыг датагаар шинжилж growth experiment санал болгоно.",
      tags: ["Growth", "Analytics", "Experiment", "Funnel"],
      highlight: "Weekly experiment board-той growth squad",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "PR & Partnership Marketer",
      companyName: "Nomad Capital Week",
      location: "Улаанбаатар",
      employmentType: "Гэрээт",
      salary: "2.9 - 3.7 сая ₮",
      description: "Media outreach, partner deal, event co-promo дээр ажиллах communication-heavy marketer хайж байна.",
      tags: ["PR", "Partnership", "Events", "Comms"],
      highlight: "Conference awareness болон sponsor visibility өсгөнө",
      level: "Mid",
      dayOffset: 3,
      hourOffset: 6,
    },
    {
      title: "Junior SEO Content Coordinator",
      companyName: "Digital Nomad Hub",
      location: "Remote",
      employmentType: "Хагас цаг",
      salary: "1.8 - 2.3 сая ₮",
      description: "Keyword brief, content upload, metadata, internal linking coordination хийх junior хайж байна.",
      tags: ["SEO Ops", "Metadata", "Brief", "CMS"],
      highlight: "Organic content machine-ийг өдөр тутам хөдөлгөнө",
      level: "Junior",
      dayOffset: 4,
    },
    {
      title: "Paid Media Creative Analyst",
      companyName: "Orange Retail",
      location: "Remote / Ulaanbaatar",
      employmentType: "Гэрээт",
      salary: "2.7 - 3.6 сая ₮",
      description: "Creative fatigue, hook analysis, ad iteration test-үүд дээр paid team-ийг дэмжинэ.",
      tags: ["Creative Analytics", "Paid Social", "Testing", "Insights"],
      highlight: "Ad creative learning loop-ийг хурдасгана",
      level: "Mid",
      dayOffset: 4,
      hourOffset: 4,
    },
    {
      title: "Senior Marketing Operations Manager",
      companyName: "Infinity Telecom",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.4 - 5.6 сая ₮",
      description: "Campaign workflow, dashboarding, attribution hygiene, agency coordination-г системжүүлнэ.",
      tags: ["Ops", "Dashboard", "Attribution", "Planning"],
      highlight: "Маркетингийн execution layer-ийг илүү production-ready болгоно",
      level: "Senior",
      dayOffset: 5,
    },
  ],
  content: [
    {
      title: "Senior Copywriter",
      companyName: "Huleg Brand Studio",
      location: "Улаанбаатар / Remote",
      employmentType: "Гэрээт",
      salary: "2.7 - 3.6 сая ₮",
      description: "Brand campaigns, landing pages, product messaging дээр ажиллах sharp copywriter авна.",
      tags: ["Copywriting", "Brand Voice", "Campaign", "Landing Page"],
      highlight: "New brand launch-ийн messaging backbone",
      level: "Senior",
      dayOffset: 0,
      hourOffset: 7,
    },
    {
      title: "Content Strategist",
      companyName: "EduPath Academy",
      location: "Remote",
      employmentType: "Бүтэн цаг",
      salary: "3.0 - 4.1 сая ₮",
      description: "Editorial calendar, content pillars, SEO brief, distribution plan-ийг owner түвшинд удирдана.",
      tags: ["Strategy", "Editorial", "SEO", "Planning"],
      highlight: "Learning brand-ийн content engine-ийг байгуулна",
      level: "Mid-Senior",
      dayOffset: 1,
      hourOffset: 4,
    },
    {
      title: "Script Writer for Short Video",
      companyName: "FrameHouse",
      location: "Улаанбаатар",
      employmentType: "Хагас цаг",
      salary: "2.1 - 2.8 сая ₮",
      description: "TikTok, Reels, YouTube Shorts-д зориулсан hook-heavy script, storyboard бичнэ.",
      tags: ["Script", "Short Video", "Hooks", "Social"],
      highlight: "Performance creative-тэй уялдсан script production",
      level: "Mid",
      dayOffset: 1,
      hourOffset: 8,
    },
    {
      title: "Technical Writer",
      companyName: "DevTemple",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "3.3 - 4.2 сая ₮",
      description: "Developer docs, onboarding guide, release note, API tutorial бэлтгэх technical writer хайж байна.",
      tags: ["Docs", "API", "Guide", "Developer Experience"],
      highlight: "Product adoption-д нөлөөлөх documentation role",
      level: "Senior",
      dayOffset: 2,
    },
    {
      title: "Bilingual Content Editor",
      companyName: "MGL Global",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "2.8 - 3.5 сая ₮",
      description: "Монгол, Англи контент edit, tone consistency, publishing QA дээр ажиллана.",
      tags: ["Editing", "Localization", "Publishing", "Bilingual"],
      highlight: "Cross-market content quality-г нэг түвшинд барина",
      level: "Mid",
      dayOffset: 2,
      hourOffset: 7,
    },
    {
      title: "Social Media Content Producer",
      companyName: "Urban Coffee Roasters",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "2.4 - 3.2 сая ₮",
      description: "Daily content shoot plan, caption, UGC coordination, weekly content calendar хөтөлнө.",
      tags: ["Social Content", "Calendar", "Caption", "UGC"],
      highlight: "Always-on content rhythm бий болгох роль",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "Article Writer for Business Media",
      companyName: "Ikon Insight",
      location: "Remote / Ulaanbaatar",
      employmentType: "Гэрээт",
      salary: "2.2 - 3.0 сая ₮",
      description: "Startup, finance, digital business сэдвээр research-backed урт нийтлэл бэлтгэнэ.",
      tags: ["Article", "Research", "Business", "Long-form"],
      highlight: "Thought leadership контент дээр төвлөрнө",
      level: "Mid",
      dayOffset: 3,
      hourOffset: 6,
    },
    {
      title: "Junior Copy Editor",
      companyName: "Bright School",
      location: "Улаанбаатар",
      employmentType: "Хагас цаг",
      salary: "1.6 - 2.1 сая ₮",
      description: "Caption, email copy, article proofreading, CMS upload дээр дэмжлэг үзүүлэх junior авна.",
      tags: ["Proofreading", "CMS", "Copy Edit", "Junior"],
      highlight: "Structured editorial process дотор өсөх боломж",
      level: "Junior",
      dayOffset: 4,
    },
    {
      title: "Podcast Show Notes Writer",
      companyName: "Voice of Asia",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "1.9 - 2.6 сая ₮",
      description: "Podcast episode summary, teaser copy, timestamps, distribution copy бэлдэнэ.",
      tags: ["Podcast", "Summary", "Distribution", "Show Notes"],
      highlight: "Audio контентыг search-friendly болгох ажил",
      level: "Mid",
      dayOffset: 4,
      hourOffset: 5,
    },
    {
      title: "Content Operations Lead",
      companyName: "Open Mongolia Portal",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "3.6 - 4.5 сая ₮",
      description: "Writers, editors, designers-тэй хамт publishing ops, QA, review cycle-ийг системчилнэ.",
      tags: ["Ops", "Workflow", "Editorial QA", "Leadership"],
      highlight: "High-volume publishing багийн process owner",
      level: "Senior",
      dayOffset: 5,
    },
  ],
  data: [
    {
      title: "Senior Data Analyst",
      companyName: "Xac Retail Intelligence",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "4.2 - 5.4 сая ₮",
      description: "Executive dashboard, cohort analysis, pricing insight дээр ажиллах data analyst хайж байна.",
      tags: ["SQL", "Power BI", "Cohort", "Dashboard"],
      highlight: "Leadership team-ийн decision dashboard-ийг owner хийж авна",
      level: "Senior",
      dayOffset: 0,
      hourOffset: 8,
    },
    {
      title: "BI Developer",
      companyName: "Erdenes Supply Chain",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "3.7 - 4.8 сая ₮",
      description: "Warehouse, sales, procurement өгөгдлийг нэгтгэсэн BI layer байгуулна.",
      tags: ["BI", "ETL", "Power BI", "Modeling"],
      highlight: "Cross-functional reporting stack байгуулах төсөл",
      level: "Mid-Senior",
      dayOffset: 1,
    },
    {
      title: "Machine Learning Engineer",
      companyName: "AI Steppe Lab",
      location: "Remote",
      employmentType: "Бүтэн цаг",
      salary: "5.0 - 6.8 сая ₮",
      description: "Recommendation and forecast models-ийг production pipeline-р ажиллуулах инженер шаардлагатай.",
      tags: ["Python", "ML", "Pipelines", "MLOps"],
      highlight: "Model-оос business impact гаргах production role",
      level: "Senior",
      dayOffset: 1,
      hourOffset: 6,
    },
    {
      title: "Data Engineer",
      companyName: "FinBridge Data",
      location: "Remote / Ulaanbaatar",
      employmentType: "Бүтэн цаг",
      salary: "4.4 - 5.7 сая ₮",
      description: "Batch + near real-time ETL, warehouse modeling, monitoring setup хийх data engineer авна.",
      tags: ["ETL", "Airflow", "Warehouse", "Monitoring"],
      highlight: "Reliable analytics foundation босгох ownership",
      level: "Senior",
      dayOffset: 2,
    },
    {
      title: "Product Analytics Specialist",
      companyName: "Mazaalai App",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "3.1 - 4.0 сая ₮",
      description: "Event tracking, funnel dashboard, experiment result synthesis дээр төвлөрнө.",
      tags: ["Product Analytics", "GA4", "Funnel", "Events"],
      highlight: "Growth squad-д embedded analytics role",
      level: "Mid",
      dayOffset: 2,
      hourOffset: 5,
    },
    {
      title: "Prompt Workflow Designer",
      companyName: "Nomad AI Services",
      location: "Remote",
      employmentType: "Гэрээт",
      salary: "3.0 - 4.1 сая ₮",
      description: "LLM-assisted internal workflow, prompt QA, evaluation rubric, human-in-loop process зохионо.",
      tags: ["LLM", "Prompting", "Evaluation", "Workflow"],
      highlight: "AI ops-ийг practical бизнес урсгалд суулгана",
      level: "Mid",
      dayOffset: 3,
    },
    {
      title: "Junior Data Analyst",
      companyName: "Insight Retail",
      location: "Улаанбаатар",
      employmentType: "Бүтэн цаг",
      salary: "2.0 - 2.8 сая ₮",
      description: "Weekly reporting, spreadsheet cleanup, SQL extract, chart update дээр ажиллах junior analyst хайж байна.",
      tags: ["SQL", "Excel", "Reporting", "Junior"],
      highlight: "Strong mentorship-тэй аналитикийн суурь role",
      level: "Junior",
      dayOffset: 3,
      hourOffset: 7,
    },
    {
      title: "Computer Vision Research Assistant",
      companyName: "Steppe Vision",
      location: "Remote",
      employmentType: "Хагас цаг",
      salary: "2.5 - 3.3 сая ₮",
      description: "Image dataset curation, model evaluation, annotation workflow дээр research support үзүүлнэ.",
      tags: ["CV", "Annotation", "Evaluation", "Research"],
      highlight: "Applied AI pilot төсөлд оролцох боломж",
      level: "Mid",
      dayOffset: 4,
    },
    {
      title: "Fraud Detection Analyst",
      companyName: "SecurePay",
      location: "Улаанбаатар / Hybrid",
      employmentType: "Бүтэн цаг",
      salary: "3.6 - 4.7 сая ₮",
      description: "Transaction monitoring, anomaly rule tuning, fraud signal dashboard ажиллуулах analyst хэрэгтэй.",
      tags: ["Fraud", "Anomaly", "SQL", "Monitoring"],
      highlight: "Risk team-ийн decision speed-ийг нэмэгдүүлнэ",
      level: "Mid-Senior",
      dayOffset: 4,
      hourOffset: 6,
    },
    {
      title: "Analytics Engineer",
      companyName: "Ger Commerce",
      location: "Remote / Ulaanbaatar",
      employmentType: "Бүтэн цаг",
      salary: "4.1 - 5.2 сая ₮",
      description: "dbt modeling, semantic layer, stakeholder-friendly marts байгуулах analytics engineer авна.",
      tags: ["dbt", "Modeling", "Semantic Layer", "SQL"],
      highlight: "Self-serve analytics-ийг дараагийн шатанд гаргана",
      level: "Senior",
      dayOffset: 5,
    },
  ],
};

export const seedLandingJobs: SeedLandingJob[] = (Object.entries(seedJobMatrix) as Array<
  [LandingCategoryKey, SeedSpec[]]
>).flatMap(([categoryKey, jobs]) =>
  jobs.map((job, index) => ({
    id: `seed-${categoryKey}-${index + 1}`,
    title: job.title,
    companyName: job.companyName,
    location: job.location,
    employmentType: job.employmentType,
    salary: job.salary,
    description: job.description,
    createdAt: seedDate(job.dayOffset, job.hourOffset),
    createdByName: null,
    categoryKey,
    tags: job.tags,
    highlight: job.highlight,
    level: job.level,
  })),
);

export const searchQuickTags = [
  { label: "Next.js", term: "Next.js" },
  { label: "UI/UX", term: "UI/UX" },
  { label: "React", term: "React" },
  { label: "Flutter", term: "Flutter" },
  { label: "SEO", term: "SEO" },
  { label: "Copywriting", term: "Copywriting" },
  { label: "SQL", term: "SQL" },
];
